spring:
  application:
    name: order-service

server:
  port: 8080
  servlet:
    context-path: /api/order-service/v1

management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  dynamodb:
    table-name: ORDER

  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events
  sqs:
    order-state-queue: order-state-queue
    order-completion-queue: order-completion-queue