spring:
  application:
    name: order-service

aws:
  dynamodb:
    table-name: ORDER

  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events
  sqs:
    order-state-queue: order-state-queue